### ISSUE TITLE
su: Authentication service cannot retrieve authentication info (Ignored)

### ISSUE THREAD

**Issue by soredake** [vaeth/portage-postsyncd-mv#2]
```
>>> Syncing repository 'hsoft' into '/var/lib/repos/hsoft'...
/usr/bin/git pull
Already up-to-date.
=== Sync completed for hsoft
 * Setting permissions 3755/0644 portage:portage for repository hsoft ... [ ok ]
su: Authentication service cannot retrieve authentication info
(Ignored)
 * Recent filestamp /var/lib/repos/hsoft/.git/git-repack.date
su: Authentication service cannot retrieve authentication info
(Ignored)
 * Updating metadata cache for the hsoft repository ...                   [ ok ]
 * Setting permissions 3755/0644 portage:portage for repository hsoft ... [ ok ]
```

**Comment by vaeth** [comment]
It seems that you are using pam, and somehow you have configured it such that "su -p portage" cannot be executed by root. On the other hand, it appears to be only a warning (because if the su would have failed, the script would have printed an error).

I do not use pam, and I do not know enough about the pam configuration to help you here.

If you cannot manage to find a good configuration, you can of course configure the scripts to not call su at all (by setting POSTSYNC_REPO_USER="** root") but of course, this means a certain security risk. (Theoretically, even an accidental bug in the script might do any damage.)
